// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Tgq8SdDcT_p4ZouLx8S2vKF3nD8MHoI',
    appId: '1:113728028333:web:4d6e3e6d5511bc7ada1024',
    messagingSenderId: '113728028333',
    projectId: 'khassab-11bed',
    authDomain: 'khassab-11bed.firebaseapp.com',
    storageBucket: 'khassab-11bed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Tgq8SdDcT_p4ZouLx8S2vKF3nD8MHoI',
    appId: '1:113728028333:android:4d6e3e6d5511bc7ada1024',
    messagingSenderId: '113728028333',
    projectId: 'khassab-11bed',
    storageBucket: 'khassab-11bed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Tgq8SdDcT_p4ZouLx8S2vKF3nD8MHoI',
    appId: '1:113728028333:ios:4d6e3e6d5511bc7ada1024',
    messagingSenderId: '113728028333',
    projectId: 'khassab-11bed',
    storageBucket: 'khassab-11bed.firebasestorage.app',
    iosBundleId: 'com.khassab.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Tgq8SdDcT_p4ZouLx8S2vKF3nD8MHoI',
    appId: '1:113728028333:macos:4d6e3e6d5511bc7ada1024',
    messagingSenderId: '113728028333',
    projectId: 'khassab-11bed',
    storageBucket: 'khassab-11bed.firebasestorage.app',
    iosBundleId: 'com.khassab.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Tgq8SdDcT_p4ZouLx8S2vKF3nD8MHoI',
    appId: '1:113728028333:windows:4d6e3e6d5511bc7ada1024',
    messagingSenderId: '113728028333',
    projectId: 'khassab-11bed',
    authDomain: 'khassab-11bed.firebaseapp.com',
    storageBucket: 'khassab-11bed.firebasestorage.app',
  );
}
